name: fxtest

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clone 
      run: git clone -b fxfileexplorer https://github.com/ungeskriptet/revanced-patches
    - name: set up zulu JDK 17 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: build
      run: cd revanced-patches && ./gradlew generateBundle
    - name: upload 
      uses: actions/upload-artifact@v3 
      with:
        name: build
        path: revanced-patches/build/*
