name: test

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-patches
        fetch-depth: 0
    - name: t3sr
      id: ser
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-integrations
        fetch-depth: 0
    - name: t3sr
      id: ger
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
    - name: write 
      run: echo '{"patches":{"url":"https://github.com/inotia00/revanced-patches/releases/download/${{ steps.ser.outputs.tag }}/revanced-patches-${{ steps.ser.outputs.tag: 1 }}.jar","version":"${{ steps.ser.outputs.tag }}"},"integrations":{"url":"https://github.com/inotia00/revanced-integrations/releases/download/v0.121.7/revanced-integrations-0.121.7.apk","version":"v0.121.7"}}'

      
