name: test

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-patches
        fetch-depth: 0
    - name: t3sr
      id: ser
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-integrations
        fetch-depth: 0
    - name: t3sr
      id: ger
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
    - id: g
      run: |
        INPUT=${{ steps.ser.outputs.tag }} echo "::set-output name=rp::${INPUT:1}"
        INPUT2=${{ steps.ger.outputs.tag }} echo "::set-output name=rp::${INPUT2:1}"

    - name: write 
      uses: DamianReeves/write-file-action@master
      env:
        rp: ${{ steps.ser.outputs.tag }}
      with:
        path: rvxf.json
        write-mode: overwrite
        contents: |
           {
             "patches": {
               "url": "https://github.com/inotia00/revanced-patches/releases/download/${{ steps.ser.outputs.tag }}/revanced-patches-${rp: 1}.jar",
               "version": "${{ steps.ser.outputs.tag }}"
            },
             "integrations": {
                 "url": "https://github.com/inotia00/revanced-integrations/releases/download/${{ steps.ger.outputs.tag }}/revanced-integrations-0.121.7.apk",
                "version": "${{ steps.ger.outputs.tag }}"
            }
           }         
    - name: upload test
      uses: actions/upload-artifact@v3
      with:
        name: f
        path: rvxf.json
      
