name: test

on:
  workflow_dispatch:

jobs:
  build:
  id: bui
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-patches
        fetch-depth: 0
    - name: t3sr
      id: ser
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - name: S
      run: echo ${{ bui.steps.ser.outputs.tag }}
