name: test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-patches
    - name: t3sr
      run: echo ${{ github.event.release.tag_name }}
    
