name: test

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-patches
        fetch-depth: 0
    - name: t3sr
      id: ser
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-integrations
        fetch-depth: 0
    - name: t3sr
      id: ger
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    

      
