name: test

on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-patches
        fetch-depth: 0
    - name: t3sr
      id: ser
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
      with:   
        repository: inotia00/revanced-integrations
        fetch-depth: 0
    - name: t3sr
      id: ger
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
    - uses: actions/checkout@v4
    - id: geck
      run: |
        INPUT=${{ steps.ser.outputs.tag }} 
        echo "::set-output name=rp::${INPUT:1}"
        INPU=${{ steps.ger.outputs.tag }} 
        echo "::set-output name=ri::${INPU:1}"
    - name: check
      run: echo ${{ steps.geck.outputs.rp }}
    - name: write 
      uses: DamianReeves/write-file-action@master
      with:
        path: rvxf.json
        write-mode: overwrite
        contents: |
           {
             "patches": {
               "url": "https://github.com/inotia00/revanced-patches/releases/download/${{ steps.ser.outputs.tag }}/revanced-patches-${{ steps.geck.outputs.rp }}.jar",
               "version": "${{ steps.ser.outputs.tag }}"
            },
             "integrations": {
                 "url": "https://github.com/inotia00/revanced-integrations/releases/download/${{ steps.ger.outputs.tag }}/revanced-integrations-${{ steps.geck.outputs.ri }}.apk",
                "version": "${{ steps.ger.outputs.tag }}"
            }
           }         
    - name: push
      uses: ad-m/github-push-action@v0.8.0
            
      
